default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: erp1_development
  username: ricardogdz1
  password: 35468
  host: localhost

test:
  <<: *default
  database: erp1_test
  username: ricardogdz1
  password: 35468
  host: localhost

production:
  <<: *default
  database: erp1_production
  username: ricardogdz1
  password: 35468
  host: localhost
